// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB91JdD9c_gXvoxbH8YUGKd3PbHQL0Uo3Q',
    appId: '1:205465714107:web:514802eeff8ced3d0e189e',
    messagingSenderId: '205465714107',
    projectId: 'loandb-c2adb',
    authDomain: 'loandb-c2adb.firebaseapp.com',
    storageBucket: 'loandb-c2adb.firebasestorage.app',
    measurementId: 'G-SNHXQDXSTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRzeQvL-am8vW5Ykyp6rEDuqcpEyfmBGs',
    appId: '1:205465714107:android:7304d5c5a12b76360e189e',
    messagingSenderId: '205465714107',
    projectId: 'loandb-c2adb',
    storageBucket: 'loandb-c2adb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmYp0Y1gjgprznKuREz3y4WfIum9iY3bw',
    appId: '1:205465714107:ios:f0a42ab3e6be34230e189e',
    messagingSenderId: '205465714107',
    projectId: 'loandb-c2adb',
    storageBucket: 'loandb-c2adb.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmYp0Y1gjgprznKuREz3y4WfIum9iY3bw',
    appId: '1:205465714107:ios:f0a42ab3e6be34230e189e',
    messagingSenderId: '205465714107',
    projectId: 'loandb-c2adb',
    storageBucket: 'loandb-c2adb.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB91JdD9c_gXvoxbH8YUGKd3PbHQL0Uo3Q',
    appId: '1:205465714107:web:9ae88d8838afd53d0e189e',
    messagingSenderId: '205465714107',
    projectId: 'loandb-c2adb',
    authDomain: 'loandb-c2adb.firebaseapp.com',
    storageBucket: 'loandb-c2adb.firebasestorage.app',
    measurementId: 'G-JJKNLQ2JF6',
  );

}