import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_project_final/auth/login.dart';
import 'package:flutter_project_final/auth/signup.dart';
import 'package:flutter_project_final/screens/admin_dashboard.dart';
import 'package:flutter_project_final/screens/userhistory.dart';
import 'package:flutter_project_final/screens/userhome.dart';
import 'package:flutter_project_final/screens/userloan.dart';
import 'package:flutter_project_final/screens/userpayment.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

void main() async { 
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Midas Touch',
      debugShowCheckedModeBanner: false,
      initialRoute: '/login',
      routes: {
       '/login': (_) => const LoginScreen(),
       '/signup': (_) => const SignupScreen(),
       '/userDashboard': (_) => const HomeScreen(),   // 👈 for normal users
       '/adminDashboard': (_) => const AdminDashboard(), // 👈 for admins
       '/userloan': (_) => const LoanPage(),
       '/userpayment': (_) => const PaymentPage(),
       '/userhistory': (_) => const HistoryPage(),
      },
    );
  }
}
