import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_project_final/auth/login.dart';
import 'package:flutter_project_final/auth/signup.dart';
import 'package:flutter_project_final/screens/admin_dashboard.dart';
import 'package:flutter_project_final/screens/loanapplications.dart';
import 'package:flutter_project_final/screens/userhistory.dart';
import 'package:flutter_project_final/screens/userhome.dart';
import 'package:flutter_project_final/screens/userloan.dart';
import 'package:flutter_project_final/screens/userpayment.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Midas Touch',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          brightness: Brightness.light,
        ),
        cardTheme: const CardThemeData(
          elevation: 4,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
        appBarTheme: const AppBarTheme(centerTitle: true, elevation: 2),
      ),
      initialRoute: '/login',
      routes: {
        '/login': (_) => const LoginScreen(),
        '/signup': (_) => const SignupScreen(),
        '/userDashboard': (_) => const HomeScreen(), // 👈 for normal users
        '/adminDashboard': (_) => const AdminDashboard(), // 👈 for admins
        '/userloan': (_) => const LoanPage(),
        '/userpayment': (_) => const PaymentPage(),
        '/userhistory': (_) => const HistoryPage(),
        '/LoanApplicationsPage': (_) => const LoanApplicationsPage(),
      },
    );
  }
}
